# Canvas settings
canvas:
  width: 1200
  height: 800

# Colors
colors:
  background: "#FFF00"
  bar: "#F1A51"

# Audio settings
audio:
  chunk_size: 1024
  transformation: "time_smoothing"
  symmetric: false
# Animation settings
animation:
  fps: 60
