# Canvas settings
canvas:
  width: 800
  height: 400

# Colors
colors:
  background: "#000000" # Black
  bar: "#FF0000" # Red

# Audio settings
audio:
  chunk_size: 500
  frame_rate: 44100

# Animation settings
animation:
  fps: 60
